###
POST http://localhost:5000/api/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "tttt",
    "lastName": "rrrrr",
    "number": 56545,
    "email": "pelon@some.com",
    "pass": "ffffff",
    "balance": 0,
    "available": 0,
    "payment": false
}



